server {
    listen 80 default_server;   # listen 80 default_server; tells Nginx to use this configuration as the default.
    root /app/public;   #root /app/public; directs Nginx to serve files from /app/public


    # This configuration tells Nginx to prioritize index.php as the default page 
    # and to process files ending in .php through the PHP service.
    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;     
    }
}